// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuahedwzdjrapxqxmibf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1YWhlZHd6ZGpyYXB4cXhtaWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDE3NTYsImV4cCI6MjA1MDY3Nzc1Nn0.6xSw2U4A2hNe44Xe1fCm82NRMht3M7I1WaR60_WfBvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);